### ISSUE TITLE
Cursor not visible on SocialAutoCompleteTextView on selecting.

### ISSUE THREAD

**Issue by rajatmehra75** [HendraAnggrian/socialview#11]
Cursor not visible on SocialAutoCompleteTextView on clicking on it, it is visible on long click or after writing anything in it.

**Comment by HendraAnggrian** [comment]
Hi @rajatmehra75, I'm currently converting this library to fully use Kotlin. I will investigate this issue once turned to Kotlin. Stay tuned!

**Comment by HendraAnggrian** [comment]
I did check the cursor, and there's nothing wrong with it, they are visible unless unfocused.

Would you mind sharing a video and your device/emulator type and OS build number?

**Comment by CripyIce** [comment]
Hi there @HendraAnggrian ,
I also do not see the cursor on lower api versions. for example, watch it on Android Studio Emulator API version 17. You can see my attachment that cursor is not visible (on API level 26 everything looks good).
Another thing, for some reason i cannot update to version 0.15.1 or 0.16.0.
Thanks!
![image](https://user-images.githubusercontent.com/26387823/28491720-8cf2bdee-6efe-11e7-903a-3282a7621bb6.png)

**Comment by HendraAnggrian** [comment]
@CripyIce I'll check it out on API 17, which I believe is Jelly Bean. In the meantime, please try version 0.15.1 as there is no 0.16.0, I must have been too sleepy yesterday.

**Comment by HendraAnggrian** [comment]
`MultiAutoCompleteTextView` weirdly behaves like that in API 17, but `AppCompatMultiAutoCompleteTextView` seems fine. All widgets are now extending appcompat-v7's widgets, effective since version 0.15.2 which has just been uploaded.

Thanks for the bug tracking guys, find me another one.

**Comment by Ravi12121212** [comment]
java.lang.IndexOutOfBoundsException: charAt: -1 < 0
        at android.text.SpannableStringBuilder.charAt(SpannableStringBuilder.java:121)
        at com.hendraanggrian.socialview.SocialViewImpl.onTextChanged(SocialViewImpl.java:300)
        at android.widget.TextView.sendOnTextChanged(TextView.java:9754)
        at android.widget.TextView.handleTextChanged(TextView.java:9851)
        at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:12509)
        at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1263)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:575)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:506)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:36)
        at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:843)
        at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:616)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:396)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
