### ISSUE TITLE
Crash on color set

### ISSUE THREAD

**Issue by CripyIce** [HendraAnggrian/socialview#19]
Hi there,
Since your latest update i get a crash on setting mention/hashtag/hyperlink colors, For example:
`commercialContentTextView.setMentionColor(Color.BLACK);`
also on this:
`commercialContentTextView.setMentionColor(Color.parseColor("#000000"));`

the error i'm getting is:
`android.content.res.Resources$NotFoundException: Resource ID #0xff000000
                                                                      at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:195)
                                                                      at android.content.res.Resources.getColor(Resources.java:949)
                                                                      at android.content.Context.getColor(Context.java:588)
                                                                      at android.support.v4.content.ContextCompat.getColor(ContextCompat.java:409)
                                                                      at com.hendraanggrian.socialview.SocialView$DefaultImpls.setMentionColor(SocialView.kt:129)
                                                                      at com.hendraanggrian.widget.SocialTextView.setMentionColor(SocialTextView.kt:12)`

Would be happy to get your attention as always :)

**Comment by HendraAnggrian** [comment]
I can't remember why, but I start keeping those colors as `ColorStateList` instead of color integers, which may have caused this issue. I guess I haven't been thorough in testing it, that's why these error reports are crucial in its development, and I thank you for it. Expect a fix in less than a day.

**Comment by CripyIce** [comment]
@HendraAnggrian thanks for the quick reply and fix!
But i'm not sure if i'm doing something wrong, but i cannot sync gradle now with version 0.16.3.

![image](https://user-images.githubusercontent.com/26387823/29423644-2d00f3a6-8385-11e7-9d48-1771cfe1b67e.png)

**Comment by CripyIce** [comment]
Hi @HendraAnggrian, my mistake!
Now works perfect! sorry for that.
