### ISSUE TITLE
AutoComplete cant inflate view

### ISSUE THREAD

**Issue by mupm1** [HendraAnggrian/socialview#3]
android.view.InflateException: Binary XML file line #9: Error inflating class TextView
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                         at io.github.hendraanggrian.socialview.commons.HashtagAdapter.getView(HashtagAdapter.java:27)
                                                                         at android.widget.AbsListView.obtainView(AbsListView.java:2263)
                                                                         at android.widget.ListPopupWindow$DropDownListView.obtainView(ListPopupWindow.java:1585)
                                                                         at android.widget.ListView.measureHeightOfChildren(ListView.java:1263)
                                                                         at android.widget.ListPopupWindow.buildDropDown(ListPopupWindow.java:1167)
                                                                         at android.widget.ListPopupWindow.show(ListPopupWindow.java:554)
                                                                         at android.widget.AutoCompleteTextView.showDropDown(AutoCompleteTextView.java:1096)
                                                                         at android.widget.AutoCompleteTextView.updateDropDownForFilter(AutoCompleteTextView.java:971)
                                                                         at android.widget.AutoCompleteTextView.onFilterComplete(AutoCompleteTextView.java:953)
                                                                         at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:285)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5045)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                         at dalvik.system.NativeStart.main(Native Method)
                                                                      Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
                                                                         at android.content.res.TypedArray.getColor(TypedArray.java:327)
                                                                         at android.widget.TextView.<init>(TextView.java:677)
                                                                         at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:60)
                                                                         at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:56)
                                                                         at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:1008)
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1067)
                                                                         at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                         at io.github.hendraanggrian.socialview.commons.HashtagAdapter.getView(HashtagAdapter.java:27) 
                                                                         at android.widget.AbsListView.obtainView(AbsListView.java:2263) 
                                                                         at android.widget.ListPopupWindow$DropDownListView.obtainView(ListPopupWindow.java:1585) 
                                                                         at android.widget.ListView.measureHeightOfChildren(ListView.java:1263) 
                                                                         at android.widget.ListPopupWindow.buildDropDown(ListPopupWindow.java:1167) 
                                                                         at android.widget.ListPopupWindow.show(ListPopupWindow.java:554) 
                                                                         at android.widget.AutoCompleteTextView.showDropDown(AutoCompleteTextView.java:1096) 
                                                                         at android.widget.AutoCompleteTextView.updateDropDownForFilter(AutoCompleteTextView.java:971) 
                                                                         at android.widget.AutoCompleteTextView.onFilterComplete(AutoCompleteTextView.java:953) 
                                                                         at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:285) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:136) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5045) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                         at dalvik.system.NativeStart.main(Native Method)

**Comment by hendraanggrian** [comment]
@mupm1 hi there, the exception message is surely helpful, but please also attach your xml and java code snippet so that I may investigate. Otherwise, I will have to close this issue.

**Comment by HendraAnggrian** [comment]
Closed for no response.
