### ISSUE TITLE
Crash when long click on hashtag or mention.

### ISSUE THREAD

**Issue by 5mi13** [hendraanggrian/socialview#41]
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.widget.Editor$SelectionModifierCursorController.getMinTouchOffset()' on a null object reference
        at android.widget.Editor.touchPositionIsInSelection(Editor.java:1084)
        at android.widget.Editor.performLongClick(Editor.java:1205)
        at android.widget.TextView.performLongClick(TextView.java:10891)
        at android.view.View.performLongClick(View.java:6322)
        at android.view.View$CheckForLongPress.run(View.java:24695)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6665)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by hendraanggrian** [comment]
I haven't thought of long click behavior. Let me first know what to do with it.

**Comment by 5mi13** [comment]
For example, you could disable the long click to avoid a failure.

**Comment by JohnnySun** [comment]
@5mi13 did u found this crash on miui when use miui system bigbong？

**Comment by JohnnySun** [comment]
I found same stacktrace on the other apps, I think is mini's hook caused this crash

**Comment by sidhuparas** [comment]
Simply setting this fixed for me:

```
textView.setOnLongClickListener { return@setOnLongClickListener true }
```

**Comment by hendraanggrian** [comment]
I've tried `setOnLongClickListener` returning `false` and `true`. In both cases, I am unable to replicate the error author has written. And since I don't have access to MIUI devices (as @JohnnySun implies) and this issue's inactivity, I'm closing this issue.
